name: my-influxdb 
version: '1.3.6' 
summary: InfluxData Snappy example
description: 
  This is a sample snap built as an example mentioned in th article Snappy Ubuntu Core for
  Embedded and IoT Devices,Open Source For You Magazine,October 2017 edition
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
apps:
  influxd:
    daemon: simple
    command: usr/bin/influxd
    plugs:
      - network-bind
parts:
  influxdb:
    plugin: dump
    source: https://dl.influxdata.com/influxdb/releases/influxdb-1.3.6_linux_i386.tar.gz
